# Generated by Django 4.0.4 on 2022-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuses',
            name='status',
            field=models.CharField(blank=True, choices=[('PA', 'Оплачен'), ('CO', 'Готовится'), ('IND', 'В доставке'), ('DE', 'Доставлен'), ('RE', 'Возврат')], default='PA', max_length=256, verbose_name='Статус заказа'),
        ),
    ]
