# Generated by Django 4.0.4 on 2022-04-26 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakecake', '0003_alter_berries_name_alter_decors_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='berries',
            field=models.ForeignKey(choices=[('NC', 'Не выбрано'), ('WO', 'Без ягод'), ('RA', 'Малина'), ('BL', 'Голубика'), ('BB', 'Ежевика'), ('ST', 'Клубника')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakecake.berries', verbose_name='Ягоды'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='decor',
            field=models.ForeignKey(choices=[('NC', 'Не выбрано'), ('WO', 'Без декора'), ('PI', ' Фисташки'), ('ME', 'Безе'), ('PE', 'Пекан'), ('MM', 'Маршмеллоу'), ('MC', 'Марципан')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakecake.decors', verbose_name='Декор'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='form',
            field=models.ForeignKey(choices=[('NC', 'Не выбрано'), ('CI', 'Круг'), ('SQ', 'Квадрат'), ('RE', 'Прямоугольник')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakecake.forms', verbose_name='Форма'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='level',
            field=models.ForeignKey(choices=[('NC', 'Не выбрано'), ('ON', 'Один'), ('TW', 'Два'), ('TH', 'Три')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakecake.levels', verbose_name='Количество уровней'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.ForeignKey(choices=[('PA', 'Оплачен'), ('CO', 'Готовится'), ('IND', 'В доставке'), ('DE', 'Доставлен'), ('RE', 'Возврат')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='bakecake.orderstatuses', verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='topping',
            field=models.ForeignKey(choices=[('NC', 'Не выбрано'), ('WO', 'Без топпинга'), ('WS', 'Белый соус'), ('CA', 'Карамельный'), ('MA', 'Кленовый'), ('BB', 'Черничный'), ('WC', 'Молочный шоколад'), ('ST', 'Клубничный')], null=True, on_delete=django.db.models.deletion.SET_NULL, to='bakecake.topping', verbose_name='Топпинг'),
        ),
    ]
